"""Settings for emencia.django.newsletter"""
import string
from django.conf import settings

USE_WORKGROUPS = getattr(settings, 'NEWSLETTER_USE_WORKGROUPS', False)
USE_UTM_TAGS = getattr(settings, 'NEWSLETTER_USE_UTM_TAGS', True)

MAILER_HARD_LIMIT = getattr(settings, 'NEWSLETTER_MAILER_HARD_LIMIT', 10000)

INCLUDE_LINKSITE = getattr(settings, 'NEWSLETTER_INCLUDE_LINKSITE', True)
INCLUDE_UNSUBSCRIPTION = getattr(settings, 'NEWSLETTER_INCLUDE_UNSUBSCRIPTION', True)

UNIQUE_KEY_LENGTH = getattr(settings, 'NEWSLETTER_UNIQUE_KEY_LENGTH', 8)
UNIQUE_KEY_CHAR_SET = getattr(settings, 'NEWSLETTER_UNIQUE_KEY_CHAR_SET', string.ascii_uppercase + string.digits)

DEFAULT_HEADER_FROM_NAME = getattr(settings, 'NEWSLETTER_DEFAULT_HEADER_FROM_NAME', 'Newsletter')
DEFAULT_HEADER_FROM_EMAIL= getattr(settings, 'NEWSLETTER_DEFAULT_HEADER_FROM_EMAIL', '<contact@ruedesecoles.com>')
DEFAULT_HEADER_REPLY_NAME = getattr(settings, 'NEWSLETTER_DEFAULT_HEADER_REPLY_NAME', 'Newsletter')
DEFAULT_HEADER_REPLY_EMAIL= getattr(settings, 'NEWSLETTER_DEFAULT_HEADER_REPLY_EMAIL', '<contact@ruedesecoles.com>')

TRACKING_LINKS = getattr(settings, 'NEWSLETTER_TRACKING_LINKS', True)
TRACKING_IMAGE = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kKEwwvINGR5lYAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC'

MEDIA_URL = getattr(settings, 'NEWSLETTER_MEDIA_URL', '/edn/')

NEWSLETTER_BASE_PATH = getattr(settings, 'NEWSLETTER_BASE_PATH', 'uploads/newsletter')
